# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Make sure files only end in a newline
      - id: double-quote-string-fixer
        name: Use single quotes
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        name: Lint (via ruff)
        args: [--fix, --exit-non-zero-on-fix, --extend-select, RUF100]
